### ISSUE TITLE
Errata for 'tsafem-pcp-book-2015.pdf'

### ISSUE THREAD

**Issue by goedman** [PetrKryslUCSD/FinEALE#1]
Section 1.3, 4th sentence: needs => need
Section 1.4, 1st sentence: time => space, or parallel => orthogonal
Section 1.5, 1st sentence: space => time

*Responses from Petr:

Parallel to the space axis means w(0,t) or w(L,t) for all t in range.
These are the boundary conditions.
Parallel to the space axis is for all 0 <= x <= L for a fixed time, i.e. initial conditions.

and:

Sorry, just noticed a typo. The second statement should read:
Parallel to the TIME axis is for all 0 <= x <= L for a fixed time, i.e. initial conditions.*

I agreed with the last 2 statements in your initial response, in x,t coordinates, the line t=t1 is parallel to the x-axis. Isn't that for a fixed t, not for all t in range?

**Comment by PetrKryslUCSD** [comment]
Boundary conditions: for all time  in range,  meaning fixed location, meaning parallel to the time axis.
Initial conditions: for all x in range, meaning fixed time, meaning parallel to the space axis.
